adding missing depencies "ipykernel" as following will fail
  File "<package_dir>/IPython/kernel/__init__.py", line 31, in <module>
    from ipykernel import comm, inprocess
ImportError: No module named ipykernel